version: "3.9"
services:
  phantomtrace:
    build: .
    container_name: phantomtrace
    stdin_open: true
    tty: true
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./config/.env:/app/config/.env
