"""Report generation: JSON and HTML export for PhantomTrace."""
import json
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List
from utils.logger import get_logger

logger = get_logger("reporter")

REPORTS_DIR = Path(__file__).parent.parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)


class Reporter:
    def __init__(self):
        self.session_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        self._results: List[Dict] = []

    def add_result(self, module: str, target: str, data: Dict):
        self._results.append({
            "module": module,
            "target": target,
            "timestamp": datetime.now().isoformat(),
            "data": data,
        })

    def _filename(self, module: str, target: str, ext: str) -> Path:
        safe_target = "".join(c if c.isalnum() or c in "-_." else "_" for c in target)
        return REPORTS_DIR / f"{self.session_id}_{module}_{safe_target}.{ext}"

    def export_json(self, module: str, target: str, data: Dict) -> Path:
        path = self._filename(module, target, "json")
        payload = {
            "phantomtrace_report": {
                "module": module,
                "target": target,
                "generated": datetime.now().isoformat(),
                "data": data,
            }
        }
        path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
        logger.info(f"JSON report saved: {path}")
        return path

    def export_html(self, module: str, target: str, data: Dict) -> Path:
        path = self._filename(module, target, "html")
        html = _build_html(module, target, data)
        path.write_text(html, encoding="utf-8")
        logger.info(f"HTML report saved: {path}")
        return path

    def export_combined_html(self, target: str) -> Path:
        safe_target = "".join(c if c.isalnum() or c in "-_." else "_" for c in target)
        path = REPORTS_DIR / f"{self.session_id}_full_{safe_target}.html"
        sections = ""
        for r in self._results:
            sections += _build_section(r["module"], r["target"], r["data"])
        html = _build_html_shell(f"Full Profile: {target}", sections)
        path.write_text(html, encoding="utf-8")
        logger.info(f"Combined HTML report saved: {path}")
        return path


def _build_html(module: str, target: str, data: Dict) -> str:
    section = _build_section(module, target, data)
    return _build_html_shell(f"{module.replace('_', ' ').title()} - {target}", section)


def _build_section(module: str, target: str, data: Dict) -> str:
    rows = _dict_to_rows(data)
    rows_html = "".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in rows)
    return f"""
    <section>
      <h2>{module.replace('_', ' ').title()}</h2>
      <p class="target">Target: <strong>{target}</strong></p>
      <table>
        <thead><tr><th>Field</th><th>Value</th></tr></thead>
        <tbody>{rows_html}</tbody>
      </table>
    </section>"""


def _dict_to_rows(data: Dict, prefix: str = "") -> list:
    rows = []
    for k, v in data.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            rows.extend(_dict_to_rows(v, key))
        elif isinstance(v, list):
            rows.append((key, ", ".join(str(i) for i in v) if v else "-"))
        else:
            rows.append((key, str(v) if v is not None else "-"))
    return rows


def _build_html_shell(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PhantomTrace - {title}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: 'Courier New', monospace; background: #0d0d0d; color: #e0e0e0; padding: 2rem; }}
    h1 {{ color: #00ccff; border-bottom: 2px solid #00ccff; padding-bottom: 0.5rem; margin-bottom: 1.5rem; }}
    h2 {{ color: #00ccff; margin: 2rem 0 0.5rem; }}
    p.target {{ color: #aaa; margin-bottom: 1rem; }}
    table {{ width: 100%; border-collapse: collapse; margin-bottom: 2rem; }}
    th {{ background: #1a1a2e; color: #00ccff; padding: 0.6rem 1rem; text-align: left; border: 1px solid #333; }}
    td {{ padding: 0.5rem 1rem; border: 1px solid #222; }}
    tr:nth-child(even) {{ background: #111; }}
    .footer {{ margin-top: 3rem; color: #555; font-size: 0.8rem; border-top: 1px solid #222; padding-top: 1rem; }}
  </style>
</head>
<body>
  <h1>PhantomTrace Report - {title}</h1>
  {body}
  <div class="footer">Generated by PhantomTrace OSINT Framework - For authorized use only</div>
</body>
</html>"""
